osmlab/editor-layer-index

Makefile
Sort order depends on the user's `LC_COLLATE`/`LC_ALL` environment variable. Different sort order results in large git commit diffs in the produced imagery.* files.
Explicitly setting a locale (here: `en_US.UTF-8`) makes the sorted output independent of user environment settings.
=> explicitly set a locale when sorting files to prevent large diffs

README.md
The project was never meant to be specific to imagery. I named it as such because that's what the majority of the layers were. Let's use a more general name. This updates the readme to reflect the more general name.
=> Update the README to reflect a more general name of the project

imagery.geojson, imagery.json, imagery.xml, sources/north-america/us/wa/SanJuanCountyWA2013Imagery.json
Aerial imagery was flown in May/June 2013 and released to public
domain. Please note the service is from an Esri ArcGIS Server which
flips the x and y order in the URL. ¯\_(ツ)_/¯
=> Add public domain imagery for San Juan County WA

sources/europe/dk/Geodatastyrelsen-Denmark.json
I spend a lot of time checking edits in Denmark and have many times suggested to new or foreign (to Denmark) mappers that they use Geodatastyrelsen imagery (currently from spring 2015 and from now on updated every year) instead of older Bing imagery. Would be very nice if Geodatastyrelsen was default imagery for Denmark.
=> Select Geodatastyrelsen as best for Denmark

sources/world/OpenStreetMap-GPS.json
I received a request today from an iD user to show the GPS direction graphically with arrows.. Here's what I made:
thoughts?
For comparison, here's what this legend looks like today:
=> Display GPS trace direction graphically

imagery.geojson, imagery.json, imagery.xml, sources/south-america/br/IBGE_DF_Adresses.json, sources/south-america/br/IBGE_DF_Mapbox_Satellite.json
I produced a layer using data from IBGE on top of Mapbox Satellite to help users to map addresses on Distrito Federal, Brazil. The data from IBGE is released in Public Domain. I published a blog post about it https://www.openstreetmap.org/user/wille/diary/39238 (Portuguese only, sorry).
=> add layer with vector data from IBGE to DF-Brazil

sources/world/HikeBike.geojson
wmflabs url is newer. hikebikemap.org also uses this. see also https://wiki.openstreetmap.org/wiki/Hike_%26_Bike_Map
updated also attribution
synchronized with josm
=> update hike bike map

imagery.geojson, imagery.json, imagery.xml, sources/europe/lu/Luxembourg-GeoportailBasemap.geojson, sources/europe/lu/Luxembourg-GeoportailCadastre.geojson, sources/europe/lu/Luxembourg-GeoportailOrtho2010.geojson, sources/europe/lu/Luxembourg-GeoportailOrtho2013.geojson, sources/europe/lu/Luxembourg-GeoportailOrtho2016.geojson, sources/europe/lu/Luxembourg-GeoportailTopo.geojson
Names shorter, and significant part now first.
=> Luxembourg imagery names now fit iD editor pane.

sources/europe/cz/IPR-orotofoto-last-tms.geojson, sources/europe/cz/IPR-orotofoto-vege-tms.geojson
Hi,
I am adding Prague ortophoto imagery from IPR, who agreed to derive data for OSM.
see https://wiki.openstreetmap.org/wiki/Cs:WikiProjekt_%C4%8Cesko/freemap#Ortofotomapy_IPR_Praha
Thanks!
=> Czechia - IPR ortofoto

sources/asia/CambodiaLaosThailandVietnambilingual.geojson
URL providing the bilingual map was changed. This updates the details to point to the current location. As zoom is provided up to 20 this is adjusted as well.
Fixes #369
=> change URL on osm-tools.org to current location

sources/europe/gb/OSOpenDataStreetView.geojson
Ref https://trac.openstreetmap.org/ticket/5484 .  
I've not tested the updated editor-imagery-index in an editor, but tiles such as https://os.openstreetmap.org/sv//15/16261/10666.png do as expected load over https.
There may of course be more changes in imagery definitions that have the same problem.
=> Change "OS OpenData StreetView" to fetch via https

sources/europe/no/Kartverket-N50-topo.geojson
N50 topographic map from "Kartverket", the Norwegian Mapping Authority.
Explicit permission filed on Norwegian OSM mailing list: [Permission](https://lists.nuug.no/pipermail/kart/2014-August/004831.html)
OSM contribution page: [Kartverket contribution](https://wiki.openstreetmap.org/wiki/Contributors#Kartverket_.28Norwegian_Mapping_Authority.29)
JOSM imagery entry: [JOSM maps](https://josm.openstreetmap.de/wiki/Maps/Norway#KartverketN50topo)
=> Add N50 topographic map for Norway

i18n/en.yaml, imagery.xml, sources/world/WMT-cycling.geojson, sources/world/WMT-hiking.geojson, sources/world/WMT-mtb.geojson, sources/world/WMT-skating.geojson, sources/world/WMT-slopemap.geojson
I prefer that waymarkedtrails attribution goes to the
site instead of a single person as there are other
contributors. Also removed reference to ODbL to make
it a bit shorter and it seems to be in line with rest
of this repo.
=> Improve waymarkedtrails attribution

requirements.txt, scripts/check.py
I broke the json schema in a new source file, and make check crashed on json.load. This changes the check script very slightly to print the file name even when the json can't be loaded.
I also added a requirements file while I was at it.
=> Better checks

schema.json
None of the editors that use ELI currently use the wms catalogs that are still quite rare. This will allow ELI contributors to create them, encouraging editors to support them.
=> Added type=wms_endpoint to schema

sources/europe/no/Kartverket-friluft.geojson, sources/europe/no/Kartverket-vegnett.geojson
Thank you for implementing WMS in iD - great feature!
Here are two very useful WMS overlays for Norway:
1) Marked hiking trails
2) Road network
Both services are provided by the Norwegian Mapping Authority (Kartverket).
[Explicit permission and discussion on the Norwegian mailing list.](https://lists.nuug.no/pipermail/kart/2014-August/004831.html)
[Overview of Norwegian import sources.](https://wiki.openstreetmap.org/wiki/Norwegian_import_sources)
=> Add two WMS overlays for Norway

sources/europe/be/BE_OrthoPhoto2016_Brussels_WMS.geojson, sources/europe/be/BE_OrthoPhoto2017_Brussels_WMS.geojson
Those are yearly release of aeriel imagery. I think I wrote it wrong on initial commit and that's why it's still 2016 aerial imagery that is displayed in iD (for instance).
This PR should fix that (unless, I'm wrong).
=> Fix `end_date` for Brussels imagery

scripts/convert_individual.py
Converts imagery data provided by JOSM to the properties `start_date` and `end_date`, see #415.
Note that for the special case `<date>2013;-</date>`, only `start_date` is set.
=> Convert date to start_date and end_date

scripts/convert_xml.py
This PR converts `start_date` and `end_date` back into `<date></date>`.
There are four different cases:
| start_date    | end_date | date (generated) |
| ---| ---| --- |
| 2013         | 2013             |    2013 |
| 2013          | 2014          |   2013;2014 |
| 2013  |    _not present_    |   2013;- |
| _not present_  |    _not present_    |   _not present_   |
A prior PR (#461) handles the conversion from JOSM `<date></date>` to `start_date` and `end_date`.
Discussion: #462 and #286
=> Convert start_date and end_date back into JOSM XML

scripts/convert_individual.py, scripts/convert_xml.py
The JOSM attributes `eli-best` and `overlay` are now mapped to GeoJSON and back into JOSM XML.
Closes #464, Discussion at #286
=> Added overlay and eli-best attribute conversion

scripts/convert_individual.py
Previously if one key was found, all of them would be written into the dict (even if they were null). Now only the keys that aren't null are written into the dict. Closes #468
=> Ignore null values for attribution-* in convert_individual.py

sources/europe/be/BE_SPW_OrthoPhoto_WMS.geojson, sources/europe/be/BE_SPW_PICC_WMS.geojson
We finally have the signed(!) license to use data from the "Service Public de Wallonie" 🎉 
I also switch to `TRANSPARENT=FALSE` because it's used as baselayer (and not overlay).
=> Update license for SPW - Wallonia (Belgium)

sources/antarctica/osmim-imagicode-S2B_R005_S69_20180222T061749.geojson, sources/asia/kz/osmim-imagicode-caspian_2018.geojson, sources/europe/de/osmim-imagicode-northsea_s2_2018.geojson, sources/europe/ru/osmim-imagicode-S2A_R021_N44_20180429T082601.geojson
New layers.
I also added a feature for self-description of the tile layers.  If you call
http://imagico.de/map/osmim_tiles.php?layer=
you get a list of layers available.  With
http://imagico.de/map/osmim_tiles.php?layer=northsea_s2_2018
you get an extended tilejson description of the layer and with 
http://imagico.de/map/osmim_tiles.php?layer=northsea_s2_2018&footprint
you get the layer footprint.
Pulling these in automatically is probably not a good idea since the main purpose of this repository is to provide a hand curated collection of layers but it might offer possibilities for more efficient updates in the future.  It might also make sense for other image layer providers to create similar descriptions.
=> new OSMIM layers from May 2018
