imagery.geojson
imagery.json
imagery.xml
sources/europe/StadtplanZrich.json

Add rough bbox to Stadtplan

---

sources/europe/dk/Geodatastyrelsen-Denmark.json

Changed DK Geodatastyrelsen TMS-proxy from GPWEB to Septima

---

Makefile
scripts/check.py
scripts/concat_geojson.py
scripts/convert.py
scripts/convert_geojson_to_legacyjson.py
scripts/convert_individual.py
scripts/convert_xml.py
scripts/geojsonify.py

This allows running `make` on Arch Linux.

Scripts require Python 2

---

sources/africa/bj/BenincotonouPleiade2016.geojson

Mark BenincotonouPleiade2016 as best image available at the polygon that it covers.
This is my first PR here; I’m following the documentation but couldn’t test the change. So it should be sensibly reviewed.

Mark BenincotonouPleiade2016 as best

---

sources/asia/jp/JapanGSI.geojson
sources/europe/ch/KantonAargau25cm-AGIS2014.geojson
sources/europe/ch/KantonBaselStadt-2015-TMS.geojson
sources/europe/ch/KantonSolothurn25cm-SOGIS2014-tms.geojson
sources/europe/ch/KantonZuerich10cm-2015-TMS.geojson
sources/europe/ch/StadtBern10cm-2016-TMS.geojson
sources/europe/ch/StadtZuerichOrthophoto2011.geojson
sources/europe/de/Bavaria-DOP80.geojson
sources/europe/es/PNOASpain-TMS.geojson
sources/europe/fr/FR-Cadastre.geojson
sources/europe/it/SouthTyrolTopomap.geojson
sources/europe/lt/Lithuania-ORT10LT.geojson
sources/north-america/us/de/Delaware2012Orthophotography.geojson
sources/north-america/us/md/MD_SixInchImagery2014.geojson
sources/north-america/us/md/MD_TransportationBasemap.geojson
sources/north-america/us/nj/NJInfrared2015.geojson
sources/north-america/us/nj/NJNatural2015.geojson
sources/north-america/us/tx/TexasOrthophoto.geojson
sources/south-america/br/IBGE_DF_Adresses.geojson
sources/world/StamenTerrainBackground.geojson

zoom is the default and used on most of the TMS sources
helps to unify and sync with the JOSM database
fixes #226

change TMS URLs with {z} to {zoom}

---

sources/north-america/us/de/Delaware2012Orthophotography.geojson

add attribution to delaware aerial imagery

---

sources/south-america/br/Rio_2013.geojson
sources/south-america/br/Rio_2015.geojson

add license url, attribution and max zoom to rio imageries

---

sources/europe/at/Basemapat.geojson
sources/europe/at/BasemapatOrthofoto.geojson

add max_zoom to basemap.at and basemap.at orthofoto

---

scripts/convert_geojson_to_legacyjson.py

This adds
- an option to generate bounding boxes from the polygons (as the original boxes got zapped in the conversion to geojson)
- an option to remove the polygons (if you don't need them it doesn't really make sense to have to parse them)
- and option to ignore WMS sources

Add some processing options to convert_geojson_to_legacyjson

---

sources/europe/ch/KantonSolothurn25cm-SOGIS2014-tms.geojson
sources/europe/ch/KantonSolothurn25cm-SOGIS2014-wms.geojson
sources/europe/ch/KantonSolothurnInfrarot125cm-SOGIS2014.geojson

update min_zoom max_zoom Solothurn imageries

---

sources/europe/at/Basemapat.geojson
sources/europe/at/BasemapatOrthofoto.geojson
sources/europe/at/GeoimageatMaxRes.geojson
sources/europe/at/GrazBasiskarte-basemap.geojson

sync with josm, detected by https://josm.openstreetmap.de/wiki/ImageryCompare

update some icon links

---

scripts/convert_xml.py

always format coordinates as floats

---

sources/world/WMT-slopemap.geojson

URL changed at some point to slopes.....

URL change

---

sources/north-america/us/USGSTopographicMaps.geojson

Switch to using amazonaws URL

---

scripts/convert_xml.py

JOSM supports `description` too.
(PR untested, just followed the logic.)

add description to convert_xml script

---

sources/north-america/us/USGSTopographicMaps.geojson

See https://github.com/osmlab/editor-layer-index/pull/290#issuecomment-288783327.

Update the USGS topo source's max zoom.

---

sources/europe/be/BE_OrthoPhoto2016_Brussels_WMS.geojson
sources/europe/be/BE_UrbISFR_Brussels_WMS.geojson
sources/europe/be/BE_UrbISNL_Brussels_WMS.geojson

add icons BE UBRIS

---

imagery.json
imagery.xml
sources/europe/ch/KantonAargau25cm-AGIS2014.geojson
sources/europe/ch/KantonAargau25cm-AGIS2016.geojson

A bit late for reasons beyond our control, but here it is.

2016 AGIS imagery

---

imagery.json
imagery.xml
sources/europe/hu/Budapest-XI-district-ortophoto-2015.geojson
sources/europe/hu/Budapest-XI-district-ortophoto-2017.geojson
sources/europe/hu/Torokbalint-ortophoto-2013.geojson
sources/europe/hu/Torokbalint-ortophoto-2015.geojson

Fixed mistakes detected by @Klumbumbus  in pull request #312

fix typos in HU imageries

---

sources/europe/hu/Hungary-FOMI-2000.geojson
sources/europe/hu/Hungary-FOMI-2005.geojson
sources/south-america/ve/landsat_233055.geojson

remove descriptions

---

sources/europe/hu/OpenStreetMap-turistautak.geojson

remove projections from TMS source

---

sources/australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-County.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-LGA.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-NPWSReserve.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-Parish.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-StateForest.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-AdministrativeBoundaries-Suburb.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-BaseMap.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-Imagery.geojson
sources/australia/au/nsw/NSW-LPI-WebServices-TopographicMap.geojson

see https://github.com/osmlab/editor-layer-index/pull/170#issuecomment-299736717

Update NSW-LPI year in attribution

---

sources/europe/lu/Luxembourg-GeoportailOrtho2010.geojson
sources/europe/lu/Luxembourg-GeoportailOrtho2013.geojson
sources/europe/lu/Luxembourg-GeoportailOrtho2016.geojson

Update URL (ending `/`)

---

sources/north-america/us/USForestService.geojson
sources/north-america/us/USGSTopographicMaps.geojson
sources/world/DigitalGlobePremiumImagery.geojson
sources/world/DigitalGlobeStandardImagery.geojson
sources/world/MapBoxSatellite.geojson

This is related to https://github.com/openstreetmap/iD/issues/4070 and 02f20f6e6cab39badc2f1e438efbbb2960e7c0fb

Switch several tile sources to https

---

imagery.xml
sources/asia/id/osmim-imagicode-LC81030632015286LGN00.geojson
sources/asia/id/osmim-imagicode-S2A_R088_S05_20160812T011732.geojson
sources/asia/kz/osmim-imagicode-aral1.geojson
sources/asia/kz/osmim-imagicode-aral2.geojson
sources/europe/de/osmim-imagicode-northsea_s2_2017.geojson
sources/europe/ru/osmim-imagicode-ndvina.geojson
sources/north-america/gl/osmim-imagicode-dms_kangerlussuaq_20151008.geojson
sources/north-america/gl/osmim-imagicode-dms_kangerlussuaq_20160518.geojson
sources/north-america/us/osmim-imagicode-LC80770232017156LGN00.geojson
sources/north-america/us/osmim-imagicode-S2A_R086_N60_20160831T213532.geojson
sources/south-america/ar/osmim-imagicode-S2A_R067_S40_20170127T140051.geojson
sources/south-america/ar/osmim-imagicode-S2A_R067_S40_20170417T140051.geojson

imagico.de OSMIM update 2017-03

---

README.md

As clarified here: https://github.com/osmlab/editor-layer-index/issues/360

Explicitely include non-imagery

---

sources/europe/fr/Toulouse-Orthophotoplan2007.geojson
sources/europe/fr/Toulouse-Orthophotoplan2011.geojson
sources/europe/fr/Toulouse-Orthophotoplan2013.geojson
sources/europe/fr/Toulouse-Orthophotoplan2015.geojson

OSM-FR TMS proxy is broken for Toulouse orthophotos, switch back to source WMS

Update Toulouse orthophotos links

---

imagery.xml
sources/antarctica/osmim-imagicode-S2A_R017_S67_20170223T022551.geojson
sources/antarctica/osmim-imagicode-S2A_R042_S78_20170214T202521.geojson
sources/antarctica/osmim-imagicode-larsen_2018.geojson
sources/europe/ch/osmim-imagicode-walps_autumn_2017.geojson

A few new osmim layers

---

CONTRIBUTING.md

I have added cmd for RedHat/Centos in CONTRIBUTING.md

add RedHat/Centos cmd in CONTRIBUTING.md

---

sources/europe/fr/CRAIG-Auvergne2013-25cm.geojson
sources/europe/fr/Geolittoral-Orthophotos2000.geojson
sources/europe/fr/GeolittoralV2-Orthophotos2010-2012.geojson
sources/europe/fr/Gobretagne-Brest2010-10cm.geojson
sources/europe/fr/Gobretagne-Morbihan2010.geojson
sources/europe/fr/Toulouse-Orthophotoplan2007.geojson
sources/europe/fr/Toulouse-Orthophotoplan2011.geojson
sources/europe/fr/Toulouse-Orthophotoplan2013.geojson
sources/europe/fr/Toulouse-Orthophotoplan2015.geojson

I have added several missing start_date and end_date for several source in France

Add missing date for several source in France

---

index.html

Make index.html explain what the golden shapes mean.

Add golden explanation

---

imagery.xml
sources/europe/be/BE_UrbISFR_Brussels_WMS.geojson
sources/europe/be/BE_UrbISNL_Brussels_WMS.geojson

See https://github.com/osmlab/editor-layer-index/pull/403#issuecomment-366525927

Updated URLs to newer (?) ELI version

---

scripts/concat_geojson.py
scripts/convert_geojson_to_legacyjson.py
scripts/convert_xml.py
scripts/util.py

Minify output

---

sources/europe/se/lantmateriet-ekonomiska.geojson
sources/europe/se/trafikverket-baninfo-main.geojson
sources/europe/se/trafikverket-baninfo-options.geojson
sources/europe/se/trafikverket-nvdb-main.geojson
sources/europe/se/trafikverket-nvdb-options.geojson
sources/europe/se/trafikverket-nvdb-streetnames.geojson

update swedish descriptions

---

sources/europe/al/openlabs-geoportal.geojson

Add the layers from [Open Labs Geoportal](https://geoportal.openlabs.cc/).

Create openlabs-geoportal.geojson (Tirana, Albania)

---

sources/europe/at/Basemapat.geojson
sources/europe/at/GeoimageatMaxRes.geojson
sources/europe/at/TirisContourlines.geojson
sources/europe/at/TirisDGM-Terrainmodel.geojson
sources/europe/at/TirisDOM-Surfacemodel.geojson
sources/europe/at/TirisOrthofoto.geojson
sources/europe/at/TirisOrthofotoCIR.geojson

This PR adds reference URLs for several layers in Austria. It also fixes one typo where the text says "goverment" instead "government". As this is my first contribution to this repository, can you please verify its correctness?

Add reference URLs for layers in Austria.

---

sources/europe/no/Kartverket-vegnett.geojson

Noticed Travis Build failed :)

Fixed Travis: Caused by a comma

---

scripts/convert_individual.py

Used "true" instead of true by mistake.

Missed a boolean conversion in convert_individual

---

scripts/util.py

Don't use projections declared within `<mirror>...</mirror>`
Fixes #467

Ignore projection within mirror (convert_individual.py)

---

sources/australia/nz/LINZ-NZ-Aerial-Imagery.geojson
sources/australia/nz/LINZ-NZ-Topo50-Gridless-Maps.geojson

updating license text as per the updated information from LINZ

LINZ data are cc by 4.0

---

sources/europe/no/Kartverket-N50-topo.geojson
sources/europe/no/Kartverket-friluft.geojson
sources/europe/no/Kartverket-vegnett.geojson

Add license_url to Norwegian imagery

---

sources/europe/no/Miljødirektoratet-Public-Recreation-Areas-overlay.geojson
sources/europe/no/NPD-Offshore-Installations-overlay.geojson

Added some entries from JOSM into ELI in an effort to contribute to #481.
Note that the use in OSM of these source is explicitly allowed, as stated in the license-url.

Added overlays for Norway
